SHELL = bash

.PHONY: all clean distclean

all: gen Makefile.ref

gen: gen.sh
	./gen.sh

Makefile.ref: Makefile.ref.header $(wildcard *.c) $(wildcard *.h)
	cp -f Makefile.ref{.header,}
	gcc -MM ./*.c ./*/*.c >> $@

clean:
	rm -f ./*.o ./*/*.o depth1

distclean: clean
	rm -rf subdir* Makefile.ref main.c
